<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\DistributorProfile;
use App\Models\ResellerProfile;
use Illuminate\Database\Seeder;

final class ResellerSeeder extends Seeder
{
    public function run(): void
    {
        // Look up distributor IDs by assigned city so resellers can be linked correctly.
        /** @var array<string, int|null> $distByCity */
        $distByCity = DistributorProfile::whereNotNull('assigned_city')
            ->whereNotNull('approved_at')
            ->pluck('id', 'assigned_city')
            ->toArray();

        $dist = static function (string $city) use ($distByCity): int|null {
            return $distByCity[$city] ?? null;
        };

        $records = [
            // ----- Metro Manila: Makati -----
            [
                'user_id'               => 'usr-res-mkt-02',
                'reseller_code'         => 'RES-MKT-002',
                'referral_code'         => 'RESMKT002',
                'first_name'            => 'Carlo',
                'last_name'             => 'Mendoza',
                'email'                 => 'carlo.mendoza@example.com',
                'phone'                 => '09171234568',
                'parent_distributor_id' => $dist('Makati'),
                'city'                  => 'Makati',
                'approved_at'           => now()->subMonths(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 62000.00,
                'bank_name'             => 'BPI',
                'bank_account_name'     => 'Carlo Mendoza',
                'bank_account_number'   => '2211334455',
                'e_wallet_gcash'        => '09171234568',
            ],
            [
                'user_id'               => 'usr-res-mkt-03',
                'reseller_code'         => 'RES-MKT-003',
                'referral_code'         => 'RESMKT003',
                'first_name'            => 'Patricia',
                'last_name'             => 'Lim',
                'email'                 => 'patricia.lim@example.com',
                'phone'                 => '09281234568',
                'parent_distributor_id' => $dist('Makati'),
                'city'                  => 'Makati',
                'approved_at'           => now()->subMonths(2),
                'approved_by'           => 'admin-001',
                'total_sales'           => 38500.00,
                'e_wallet_maya'         => '09281234568',
            ],
            [
                'user_id'               => null,
                'reseller_code'         => 'RES-MKT-004',
                'referral_code'         => 'RESMKT004',
                'first_name'            => 'Jerome',
                'last_name'             => 'Ong',
                'email'                 => 'jerome.ong@example.com',
                'phone'                 => '09151234570',
                'parent_distributor_id' => $dist('Makati'),
                'city'                  => 'Makati',
                'approved_at'           => null,   // pending
                'total_sales'           => 0.00,
            ],

            // ----- Metro Manila: Quezon City -----
            [
                'user_id'               => 'usr-res-qc-03',
                'reseller_code'         => 'RES-QC-003',
                'referral_code'         => 'RESQC003',
                'first_name'            => 'Maribel',
                'last_name'             => 'Garcia',
                'email'                 => 'maribel.garcia@example.com',
                'phone'                 => '09179876543',
                'parent_distributor_id' => $dist('Quezon City'),
                'city'                  => 'Quezon City',
                'approved_at'           => now()->subMonths(4),
                'approved_by'           => 'admin-001',
                'total_sales'           => 51000.00,
                'bank_name'             => 'BDO',
                'bank_account_name'     => 'Maribel Garcia',
                'bank_account_number'   => '3322445566',
                'e_wallet_gcash'        => '09179876543',
            ],
            [
                'user_id'               => 'usr-res-qc-04',
                'reseller_code'         => 'RES-QC-004',
                'referral_code'         => 'RESQC004',
                'first_name'            => 'Ryan',
                'last_name'             => 'Santos',
                'email'                 => 'ryan.santos@example.com',
                'phone'                 => '09289876543',
                'parent_distributor_id' => $dist('Quezon City'),
                'city'                  => 'Quezon City',
                'approved_at'           => now()->subMonths(2),
                'approved_by'           => 'admin-001',
                'total_sales'           => 27500.00,
                'e_wallet_maya'         => '09289876543',
            ],
            [
                'user_id'               => null,
                'reseller_code'         => 'RES-QC-005',
                'referral_code'         => 'RESQC005',
                'first_name'            => 'Jessa',
                'last_name'             => 'Reyes',
                'email'                 => 'jessa.reyes@example.com',
                'phone'                 => '09159876544',
                'parent_distributor_id' => $dist('Quezon City'),
                'city'                  => 'Quezon City',
                'approved_at'           => null,
                'total_sales'           => 0.00,
            ],

            // ----- Metro Manila: Manila -----
            [
                'user_id'               => 'usr-res-mla-01',
                'reseller_code'         => 'RES-MLA-001',
                'referral_code'         => 'RESMLA001',
                'first_name'            => 'Ligaya',
                'last_name'             => 'dela Cruz',
                'email'                 => 'ligaya.delacruz@example.com',
                'phone'                 => '09175551234',
                'parent_distributor_id' => $dist('Manila'),
                'city'                  => 'Manila',
                'approved_at'           => now()->subMonths(5),
                'approved_by'           => 'admin-001',
                'total_sales'           => 73000.00,
                'bank_name'             => 'Metrobank',
                'bank_account_name'     => 'Ligaya dela Cruz',
                'bank_account_number'   => '4433556677',
                'e_wallet_gcash'        => '09175551234',
            ],
            [
                'user_id'               => 'usr-res-mla-02',
                'reseller_code'         => 'RES-MLA-002',
                'referral_code'         => 'RESMLA002',
                'first_name'            => 'Bernard',
                'last_name'             => 'Navarro',
                'email'                 => 'bernard.navarro@example.com',
                'phone'                 => '09285551234',
                'parent_distributor_id' => $dist('Manila'),
                'city'                  => 'Manila',
                'approved_at'           => now()->subMonths(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 44000.00,
                'e_wallet_maya'         => '09285551234',
            ],
            [
                'user_id'               => 'usr-res-mla-03',
                'reseller_code'         => 'RES-MLA-003',
                'referral_code'         => 'RESMLA003',
                'first_name'            => 'Cristina',
                'last_name'             => 'Aguilar',
                'email'                 => 'cristina.aguilar@example.com',
                'phone'                 => '09155551235',
                'parent_distributor_id' => $dist('Manila'),
                'city'                  => 'Manila',
                'approved_at'           => now()->subMonths(1),
                'approved_by'           => 'admin-001',
                'total_sales'           => 19500.00,
                'bank_name'             => 'BDO',
                'bank_account_name'     => 'Cristina Aguilar',
                'bank_account_number'   => '5544667788',
                'e_wallet_gcash'        => '09155551235',
            ],

            // ----- Metro Manila: Taguig -----
            [
                'user_id'               => 'usr-res-tgu-01',
                'reseller_code'         => 'RES-TGU-001',
                'referral_code'         => 'RESTGU001',
                'first_name'            => 'Winston',
                'last_name'             => 'Dela Torre',
                'email'                 => 'winston.delatorre@example.com',
                'phone'                 => '09176667788',
                'parent_distributor_id' => $dist('Taguig'),
                'city'                  => 'Taguig',
                'approved_at'           => now()->subMonths(4),
                'approved_by'           => 'admin-001',
                'total_sales'           => 58000.00,
                'bank_name'             => 'BPI',
                'bank_account_name'     => 'Winston Dela Torre',
                'bank_account_number'   => '6655778899',
                'e_wallet_gcash'        => '09176667788',
            ],
            [
                'user_id'               => 'usr-res-tgu-02',
                'reseller_code'         => 'RES-TGU-002',
                'referral_code'         => 'RESTGU002',
                'first_name'            => 'Sheila',
                'last_name'             => 'Ocampo',
                'email'                 => 'sheila.ocampo@example.com',
                'phone'                 => '09286667788',
                'parent_distributor_id' => $dist('Taguig'),
                'city'                  => 'Taguig',
                'approved_at'           => now()->subWeeks(6),
                'approved_by'           => 'admin-001',
                'total_sales'           => 23000.00,
                'e_wallet_maya'         => '09286667788',
            ],

            // ----- Metro Manila: Pasig -----
            [
                'user_id'               => 'usr-res-psg-01',
                'reseller_code'         => 'RES-PSG-001',
                'referral_code'         => 'RESPSG001',
                'first_name'            => 'Florinda',
                'last_name'             => 'Castillo',
                'email'                 => 'florinda.castillo@example.com',
                'phone'                 => '09177778899',
                'parent_distributor_id' => $dist('Pasig'),
                'city'                  => 'Pasig',
                'approved_at'           => now()->subMonths(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 36000.00,
                'bank_name'             => 'UnionBank',
                'bank_account_name'     => 'Florinda Castillo',
                'bank_account_number'   => '7766889900',
                'e_wallet_gcash'        => '09177778899',
            ],
            [
                'user_id'               => null,
                'reseller_code'         => 'RES-PSG-002',
                'referral_code'         => 'RESPSG002',
                'first_name'            => 'Noel',
                'last_name'             => 'Yap',
                'email'                 => 'noel.yap@example.com',
                'phone'                 => '09287778899',
                'parent_distributor_id' => $dist('Pasig'),
                'city'                  => 'Pasig',
                'approved_at'           => null,
                'total_sales'           => 0.00,
            ],

            // ----- Metro Manila: Marikina -----
            [
                'user_id'               => 'usr-res-mrk-01',
                'reseller_code'         => 'RES-MRK-001',
                'referral_code'         => 'RESMRK001',
                'first_name'            => 'Imelda',
                'last_name'             => 'Ramos',
                'email'                 => 'imelda.ramos@example.com',
                'phone'                 => '09171239876',
                'parent_distributor_id' => null,
                'city'                  => 'Marikina',
                'approved_at'           => now()->subMonths(2),
                'approved_by'           => 'admin-001',
                'total_sales'           => 15000.00,
                'e_wallet_gcash'        => '09171239876',
            ],

            // ----- Metro Manila: Parañaque -----
            [
                'user_id'               => 'usr-res-prq-01',
                'reseller_code'         => 'RES-PRQ-001',
                'referral_code'         => 'RESPRQ001',
                'first_name'            => 'Danilo',
                'last_name'             => 'Reyes',
                'email'                 => 'danilo.reyes@example.com',
                'phone'                 => '09281239876',
                'parent_distributor_id' => null,
                'city'                  => 'Parañaque',
                'approved_at'           => now()->subMonths(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 22500.00,
                'bank_name'             => 'BDO',
                'bank_account_name'     => 'Danilo Reyes',
                'bank_account_number'   => '8877990011',
                'e_wallet_gcash'        => '09281239876',
            ],

            // ----- Metro Manila: Las Piñas -----
            [
                'user_id'               => 'usr-res-lsp-01',
                'reseller_code'         => 'RES-LSP-001',
                'referral_code'         => 'RESLSP001',
                'first_name'            => 'Adelaida',
                'last_name'             => 'Villafuerte',
                'email'                 => 'adelaida.villafuerte@example.com',
                'phone'                 => '09151239877',
                'parent_distributor_id' => null,
                'city'                  => 'Las Piñas',
                'approved_at'           => now()->subWeeks(5),
                'approved_by'           => 'admin-001',
                'total_sales'           => 17500.00,
                'e_wallet_maya'         => '09151239877',
            ],

            // ----- Metro Manila: Muntinlupa -----
            [
                'user_id'               => 'usr-res-mun-01',
                'reseller_code'         => 'RES-MUN-001',
                'referral_code'         => 'RESMUN001',
                'first_name'            => 'Rodolfo',
                'last_name'             => 'Sta. Maria',
                'email'                 => 'rodolfo.stamaria@example.com',
                'phone'                 => '09171240000',
                'parent_distributor_id' => null,
                'city'                  => 'Muntinlupa',
                'approved_at'           => now()->subWeeks(8),
                'approved_by'           => 'admin-001',
                'total_sales'           => 31000.00,
                'bank_name'             => 'Metrobank',
                'bank_account_name'     => 'Rodolfo Sta. Maria',
                'bank_account_number'   => '9988001122',
                'e_wallet_gcash'        => '09171240000',
            ],

            // ----- Metro Manila: Caloocan -----
            [
                'user_id'               => 'usr-res-cal-01',
                'reseller_code'         => 'RES-CAL-001',
                'referral_code'         => 'RESCAL001',
                'first_name'            => 'Socorro',
                'last_name'             => 'Dizon',
                'email'                 => 'socorro.dizon@example.com',
                'phone'                 => '09281240001',
                'parent_distributor_id' => null,
                'city'                  => 'Caloocan',
                'approved_at'           => now()->subMonths(2),
                'approved_by'           => 'admin-001',
                'total_sales'           => 13500.00,
                'e_wallet_gcash'        => '09281240001',
            ],

            // ----- Metro Manila: Valenzuela -----
            [
                'user_id'               => 'usr-res-val-01',
                'reseller_code'         => 'RES-VAL-001',
                'referral_code'         => 'RESVAL001',
                'first_name'            => 'Herminia',
                'last_name'             => 'Buenaventura',
                'email'                 => 'herminia.buenaventura@example.com',
                'phone'                 => '09151240002',
                'parent_distributor_id' => null,
                'city'                  => 'Valenzuela',
                'approved_at'           => now()->subWeeks(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 9800.00,
                'e_wallet_maya'         => '09151240002',
            ],

            // ----- Cebu City -----
            [
                'user_id'               => 'usr-res-ceb-02',
                'reseller_code'         => 'RES-CEB-002',
                'referral_code'         => 'RESCEB002',
                'first_name'            => 'Lourdes',
                'last_name'             => 'Magbanua',
                'email'                 => 'lourdes.magbanua@example.com',
                'phone'                 => '09323331234',
                'parent_distributor_id' => $dist('Cebu City'),
                'city'                  => 'Cebu City',
                'approved_at'           => now()->subMonths(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 47000.00,
                'bank_name'             => 'BDO',
                'bank_account_name'     => 'Lourdes Magbanua',
                'bank_account_number'   => '1100223344',
                'e_wallet_gcash'        => '09323331234',
            ],
            [
                'user_id'               => 'usr-res-ceb-03',
                'reseller_code'         => 'RES-CEB-003',
                'referral_code'         => 'RESCEB003',
                'first_name'            => 'Aldwin',
                'last_name'             => 'Tabios',
                'email'                 => 'aldwin.tabios@example.com',
                'phone'                 => '09433331234',
                'parent_distributor_id' => $dist('Cebu City'),
                'city'                  => 'Cebu City',
                'approved_at'           => now()->subMonths(1),
                'approved_by'           => 'admin-001',
                'total_sales'           => 24000.00,
                'e_wallet_maya'         => '09433331234',
            ],
            [
                'user_id'               => null,
                'reseller_code'         => 'RES-CEB-004',
                'referral_code'         => 'RESCEB004',
                'first_name'            => 'Marissa',
                'last_name'             => 'Padilla',
                'email'                 => 'marissa.padilla@example.com',
                'phone'                 => '09553331235',
                'parent_distributor_id' => $dist('Cebu City'),
                'city'                  => 'Cebu City',
                'approved_at'           => null,
                'total_sales'           => 0.00,
            ],

            // ----- Davao City -----
            [
                'user_id'               => 'usr-res-dva-01',
                'reseller_code'         => 'RES-DVA-001',
                'referral_code'         => 'RESDVA001',
                'first_name'            => 'Erlinda',
                'last_name'             => 'Manalastas',
                'email'                 => 'erlinda.manalastas@example.com',
                'phone'                 => '09224445566',
                'parent_distributor_id' => $dist('Davao City'),
                'city'                  => 'Davao City',
                'approved_at'           => now()->subMonths(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 41000.00,
                'bank_name'             => 'UnionBank',
                'bank_account_name'     => 'Erlinda Manalastas',
                'bank_account_number'   => '2211334455',
                'e_wallet_gcash'        => '09224445566',
            ],
            [
                'user_id'               => 'usr-res-dva-02',
                'reseller_code'         => 'RES-DVA-002',
                'referral_code'         => 'RESDVA002',
                'first_name'            => 'Percival',
                'last_name'             => 'Sabado',
                'email'                 => 'percival.sabado@example.com',
                'phone'                 => '09334445566',
                'parent_distributor_id' => $dist('Davao City'),
                'city'                  => 'Davao City',
                'approved_at'           => now()->subWeeks(5),
                'approved_by'           => 'admin-001',
                'total_sales'           => 16500.00,
                'e_wallet_maya'         => '09334445566',
            ],

            // ----- Cagayan de Oro -----
            [
                'user_id'               => 'usr-res-cdo-01',
                'reseller_code'         => 'RES-CDO-001',
                'referral_code'         => 'RESCDO001',
                'first_name'            => 'Virgilita',
                'last_name'             => 'Cinco',
                'email'                 => 'virgilita.cinco@example.com',
                'phone'                 => '09425556677',
                'parent_distributor_id' => $dist('Cagayan de Oro'),
                'city'                  => 'Cagayan de Oro',
                'approved_at'           => now()->subWeeks(8),
                'approved_by'           => 'admin-001',
                'total_sales'           => 28000.00,
                'bank_name'             => 'Landbank',
                'bank_account_name'     => 'Virgilita Cinco',
                'bank_account_number'   => '3322445566',
                'e_wallet_gcash'        => '09425556677',
            ],
            [
                'user_id'               => null,
                'reseller_code'         => 'RES-CDO-002',
                'referral_code'         => 'RESCDO002',
                'first_name'            => 'Alberto',
                'last_name'             => 'Pascua',
                'email'                 => 'alberto.pascua@example.com',
                'phone'                 => '09535556677',
                'parent_distributor_id' => $dist('Cagayan de Oro'),
                'city'                  => 'Cagayan de Oro',
                'approved_at'           => null,
                'total_sales'           => 0.00,
            ],

            // ----- Iloilo City -----
            [
                'user_id'               => 'usr-res-ilo-01',
                'reseller_code'         => 'RES-ILO-001',
                'referral_code'         => 'RESILO001',
                'first_name'            => 'Concepcion',
                'last_name'             => 'Flores',
                'email'                 => 'concepcion.flores@example.com',
                'phone'                 => '09336667788',
                'parent_distributor_id' => $dist('Iloilo City'),
                'city'                  => 'Iloilo City',
                'approved_at'           => now()->subWeeks(6),
                'approved_by'           => 'admin-001',
                'total_sales'           => 18000.00,
                'e_wallet_gcash'        => '09336667788',
            ],

            // ----- Bacolod -----
            [
                'user_id'               => 'usr-res-bcd-01',
                'reseller_code'         => 'RES-BCD-001',
                'referral_code'         => 'RESBCD001',
                'first_name'            => 'Clarita',
                'last_name'             => 'Hilario',
                'email'                 => 'clarita.hilario@example.com',
                'phone'                 => '09347778899',
                'parent_distributor_id' => $dist('Bacolod'),
                'city'                  => 'Bacolod',
                'approved_at'           => now()->subWeeks(4),
                'approved_by'           => 'admin-001',
                'total_sales'           => 12500.00,
                'bank_name'             => 'BPI',
                'bank_account_name'     => 'Clarita Hilario',
                'bank_account_number'   => '4433556677',
                'e_wallet_maya'         => '09347778899',
            ],

            // ----- Angeles City -----
            [
                'user_id'               => 'usr-res-ang-01',
                'reseller_code'         => 'RES-ANG-001',
                'referral_code'         => 'RESANG001',
                'first_name'            => 'Simplicio',
                'last_name'             => 'Guzon',
                'email'                 => 'simplicio.guzon@example.com',
                'phone'                 => '09158889900',
                'parent_distributor_id' => $dist('Angeles City'),
                'city'                  => 'Angeles City',
                'approved_at'           => now()->subWeeks(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 11000.00,
                'e_wallet_gcash'        => '09158889900',
            ],

            // ----- Antipolo -----
            [
                'user_id'               => 'usr-res-ant-01',
                'reseller_code'         => 'RES-ANT-001',
                'referral_code'         => 'RESANT001',
                'first_name'            => 'Salvacion',
                'last_name'             => 'Miranda',
                'email'                 => 'salvacion.miranda@example.com',
                'phone'                 => '09169990011',
                'parent_distributor_id' => $dist('Antipolo'),
                'city'                  => 'Antipolo',
                'approved_at'           => now()->subWeeks(2),
                'approved_by'           => 'admin-001',
                'total_sales'           => 8500.00,
                'e_wallet_maya'         => '09169990011',
            ],

            // ----- General Santos -----
            [
                'user_id'               => 'usr-res-gsc-01',
                'reseller_code'         => 'RES-GSC-001',
                'referral_code'         => 'RESGSC001',
                'first_name'            => 'Benhur',
                'last_name'             => 'Tañada',
                'email'                 => 'benhur.tanada@example.com',
                'phone'                 => '09270001122',
                'parent_distributor_id' => $dist('General Santos'),
                'city'                  => 'General Santos',
                'approved_at'           => now()->subWeeks(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 9200.00,
                'bank_name'             => 'Landbank',
                'bank_account_name'     => 'Benhur Tañada',
                'bank_account_number'   => '5544667788',
                'e_wallet_gcash'        => '09270001122',
            ],

            // ----- Baguio -----
            [
                'user_id'               => 'usr-res-bag-01',
                'reseller_code'         => 'RES-BAG-001',
                'referral_code'         => 'RESBAG001',
                'first_name'            => 'Melanie',
                'last_name'             => 'Corpuz',
                'email'                 => 'melanie.corpuz@example.com',
                'phone'                 => '09181112233',
                'parent_distributor_id' => $dist('Baguio'),
                'city'                  => 'Baguio',
                'approved_at'           => now()->subWeeks(2),
                'approved_by'           => 'admin-001',
                'total_sales'           => 7500.00,
                'e_wallet_gcash'        => '09181112233',
            ],

            // ----- Bacoor (Cavite) -----
            [
                'user_id'               => 'usr-res-bac-01',
                'reseller_code'         => 'RES-BAC-001',
                'referral_code'         => 'RESBAC001',
                'first_name'            => 'Nestor',
                'last_name'             => 'Alcantara',
                'email'                 => 'nestor.alcantara@example.com',
                'phone'                 => '09292223344',
                'parent_distributor_id' => null,
                'city'                  => 'Bacoor',
                'approved_at'           => now()->subWeeks(4),
                'approved_by'           => 'admin-001',
                'total_sales'           => 14200.00,
                'e_wallet_maya'         => '09292223344',
            ],

            // ----- Santa Rosa (Laguna) -----
            [
                'user_id'               => 'usr-res-str-01',
                'reseller_code'         => 'RES-STR-001',
                'referral_code'         => 'RESSTR001',
                'first_name'            => 'Wilhelmina',
                'last_name'             => 'Salazar',
                'email'                 => 'wilhelmina.salazar@example.com',
                'phone'                 => '09403334455',
                'parent_distributor_id' => null,
                'city'                  => 'Santa Rosa',
                'approved_at'           => now()->subWeeks(6),
                'approved_by'           => 'admin-001',
                'total_sales'           => 20000.00,
                'bank_name'             => 'BDO',
                'bank_account_name'     => 'Wilhelmina Salazar',
                'bank_account_number'   => '6655778899',
                'e_wallet_gcash'        => '09403334455',
            ],

            // ----- Lipa (Batangas) -----
            [
                'user_id'               => 'usr-res-lip-01',
                'reseller_code'         => 'RES-LIP-001',
                'referral_code'         => 'RESLIP001',
                'first_name'            => 'Alfredo',
                'last_name'             => 'Tolentino',
                'email'                 => 'alfredo.tolentino@example.com',
                'phone'                 => '09514445566',
                'parent_distributor_id' => null,
                'city'                  => 'Lipa',
                'approved_at'           => now()->subWeeks(3),
                'approved_by'           => 'admin-001',
                'total_sales'           => 11800.00,
                'e_wallet_maya'         => '09514445566',
            ],

            // ----- Tacloban -----
            [
                'user_id'               => 'usr-res-tcl-01',
                'reseller_code'         => 'RES-TCL-001',
                'referral_code'         => 'RESTCL001',
                'first_name'            => 'Resurreccion',
                'last_name'             => 'Palma',
                'email'                 => 'resurreccion.palma@example.com',
                'phone'                 => '09325556677',
                'parent_distributor_id' => null,
                'city'                  => 'Tacloban',
                'approved_at'           => now()->subWeeks(5),
                'approved_by'           => 'admin-001',
                'total_sales'           => 8900.00,
                'e_wallet_gcash'        => '09325556677',
            ],

            // ----- Lucena (Quezon Province) -----
            [
                'user_id'               => 'usr-res-luc-01',
                'reseller_code'         => 'RES-LUC-001',
                'referral_code'         => 'RESLUC001',
                'first_name'            => 'Bonifacio',
                'last_name'             => 'Enriquez',
                'email'                 => 'bonifacio.enriquez@example.com',
                'phone'                 => '09436667788',
                'parent_distributor_id' => null,
                'city'                  => 'Lucena',
                'approved_at'           => now()->subWeeks(7),
                'approved_by'           => 'admin-001',
                'total_sales'           => 6700.00,
                'e_wallet_maya'         => '09436667788',
            ],

            // ----- Naga (Camarines Sur) -----
            [
                'user_id'               => 'usr-res-nag-01',
                'reseller_code'         => 'RES-NAG-001',
                'referral_code'         => 'RESNAG001',
                'first_name'            => 'Presentacion',
                'last_name'             => 'Badillo',
                'email'                 => 'presentacion.badillo@example.com',
                'phone'                 => '09547778899',
                'parent_distributor_id' => null,
                'city'                  => 'Naga',
                'approved_at'           => null,
                'total_sales'           => 0.00,
            ],
        ];

        foreach ($records as $data) {
            ResellerProfile::create($data);
        }
    }
}
